### ISSUE TITLE
Merge Targets Invalid Argument foreach()

### ISSUE THREAD

**Issue by cyberperspectives** [cyberperspectives/sagacity#3] opened 2018-08-16 17:31 UTC
If you try to merge two targets, you get the following error and the targets do not merge:

Invalid argument supplied foreach() in database.inc line 11887
count() parameter must be an array or an object that implements Countable in database.inc line 12207

**Comment by godsgood33** [comment] 2018-08-21 21:35
I don't see a for loop at either of those line numbers in database.inc.  Can you please let me know what function this is coming from?

**Comment by JeffOdegard** [comment] 2018-09-05 17:07
Couldn't reproduce in latest 1.3.3 dev version.  Closing this issue.

**Closed by JeffOdegard** 2018-09-05 17:07 UTC
Labels: bug
